---
title: "Battleship NJ"
output: html_document
date: "2025-04-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r set working directory}

setwd("C:/Users/jyan/OneDrive - Econsult Solutions Inc/Battleship NJ - Proforma Analysis")

```

```{r packages}

library(data.table)
library(dplyr)
library(kableExtra)
library(lubridate)
library(ggplot2)
library(tidycensus)
library(tidyverse)
library(httr)

sf::sf_use_s2(FALSE)

```

```{r}

#Data dictionary that I am using: https://api.census.gov/data/2023/acs/acs5/groups/B25001.html

#checking stuff
#pulls GEOID, NAME (name of the census tract), B25001_001E (Estimate!!Total), B25001_001M (Margin of Error!!Total)

nj_2023 =  get_acs(
  geography = "place",
  variables = "B01003_001", #total population
  year = 2023,
  output = "wide",
  state = "34", #NJ State FIPS code is 34
  county = NULL, #not needed for place-level data
  survey = "acs5",
#  geometry = TRUE,
  ) #house_total

camden_2023 = nj_2023 %>%
  filter(NAME == "Camden city, New Jersey")

```

Population: B01003_001 https://api.census.gov/data/2023/acs/acs5/groups/B01003.html
Occupied housing units: B25002_002 https://api.census.gov/data/2023/acs/acs5/groups/B25002.html
Owner occupied: B25003_002 https://api.census.gov/data/2023/acs/acs5/groups/B25003.html
Renter occupied: B25003_003 https://api.census.gov/data/2023/acs/acs5/groups/B25003.html
Median housing value: B25077_001 https://api.census.gov/data/2023/acs/acs5/groups/B25077.html
Median household income: B19013_001 https://api.census.gov/data/2023/acs/acs5/groups/B19013.html

```{r ACS data}

acs_data = function(geography,
                                   year,
                                   state,
                                   county,
                                   geometry,
                                   survey){
  
    relevant_vars <- c(
      "B01003_001E", #population
      "B25002_002E", #occupied housing units
      "B25003_002E", #owner occupied
      "B25003_003E", #renter occupied
      "B25077_001E", #median housing value
      "B19013_001E" #median household income
    )
  
  data_structured <- get_acs(
  geography = geography,
  variables = relevant_vars,
  year = year, 
  state = state, 
  county = county,
  geometry = geometry,
  survey = survey,
  output = "wide") %>%
    
  transmute(
    GEOID, 
    NAME,
    population = B01003_001E,
    occupied_housing_units = B25002_002E,
    owner_occupied = B25003_002E,
    renter_occupied = B25003_003E,
    median_housing_value = B25077_001E,
    median_household_income = B19013_001E
    )
  
  return(data_structured)
  }

```

```{r}

data_2023 = acs_data("place", 2023, "34", NULL, FALSE, "acs5")
data_2022 = acs_data("place", 2022, "34", NULL, FALSE, "acs5")
data_2021 = acs_data("place", 2021, "34", NULL, FALSE, "acs5")
data_2020 = acs_data("place", 2020, "34", NULL, FALSE, "acs5")
data_2019 = acs_data("place", 2019, "34", NULL, FALSE, "acs5")
data_2018 = acs_data("place", 2018, "34", NULL, FALSE, "acs5")
data_2017 = acs_data("place", 2017, "34", NULL, FALSE, "acs5")
data_2016 = acs_data("place", 2016, "34", NULL, FALSE, "acs5")
data_2015 = acs_data("place", 2015, "34", NULL, FALSE, "acs5")
data_2014 = acs_data("place", 2014, "34", NULL, FALSE, "acs5")
data_2013 = acs_data("place", 2013, "34", NULL, FALSE, "acs5")

```
```{r}

# adding year variables

data_2023 <- data_2023 %>%
  mutate(year = 2023)

data_2022 <- data_2022 %>%
  mutate(year = 2022)

data_2021 <- data_2021 %>%
  mutate(year = 2021)

data_2020 <- data_2020 %>%
  mutate(year = 2020)

data_2019 <- data_2019 %>%
  mutate(year = 2019)

data_2018 <- data_2018 %>%
  mutate(year = 2018)

data_2017 <- data_2017 %>%
  mutate(year = 2017)

data_2016 <- data_2016 %>%
  mutate(year = 2016)

data_2015 <- data_2015 %>%
  mutate(year = 2015)

data_2014 <- data_2014 %>%
  mutate(year = 2014)

data_2013 <- data_2013 %>%
  mutate(year = 2013)

```

```{r}

combined_dataframes = rbind(data_2023, data_2022, data_2021, data_2020, data_2019, data_2018, data_2017, data_2016, data_2015, data_2014, data_2013)
  
```


```{r}

camden_acs = combined_dataframes %>%
  filter(NAME == "Camden city, New Jersey")

```

```{r}
#export

write.csv(camden_acs, "camden_data.csv", row.names = FALSE)

```

